spring.application.name=todo
spring.datasource.url=jdbc:sqlite:tasks.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update

# Point to the correct community package path:
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect